# Generated by Django 5.2.7 on 2025-11-19 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_last_name'),
        ('orders', '0008_order_advance_amount_alter_order_current_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_shirt_cutter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shirt_cutter_orders', to='employees.employee', verbose_name='Цамцны эсгүүрчин'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_shirt_sewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shirt_sewer_orders', to='employees.employee', verbose_name='Цамцны оёдолчин'),
        ),
        migrations.AddField(
            model_name='order',
            name='has_shirt',
            field=models.BooleanField(default=False, verbose_name='Цамцтай'),
        ),
    ]
